#! /bin/sh

sxhkd &

# polybar

 ~/.config/polybar/launch.sh &

# compositing and wallpaper 

picom & 
xrdb merge ~/.Xresources &  # (terminal theme)

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         4
bspc config window_gap          12
bsp config presel_feedback_color "#ffffff" 
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=tiling follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a "osu!.exe" state=floating
bspc config top_padding 25

bspc config focused_border_color "#f5cde3"
bspc config normal_border_color "#a76792"

feh --bg-fill ~/Downloads/1130518.png
